### ISSUE TITLE
doesn't compile with 4.2.1 alpha  -version  8.4.0.20180118

### ISSUE THREAD

**Issue by GeorgeCo** [haskell-suite/haskell-src-exts#399]
not sure when it is planned to make the library compatible with 8.4.1
fwiw current errors are 

src/Language/Haskell/Exts/Pretty.hs:253:39: error:
    Ambiguous occurrence ‘<>’
    It could refer to either ‘Prelude.<>’,
                             imported from ‘Prelude’ at src/Language/Haskell/Exts/Pretty.hs:34:1-27
                             (and originally defined in ‘GHC.Base’)
                          or ‘Language.Haskell.Exts.Pretty.<>’,
                             defined at src/Language/Haskell/Exts/Pretty.hs:226:4
    |
253 |                      go d (e:es) = (d <> p) : go e es
    |   
...

**Comment by mpickering** [comment]
I have fixed this on master and cut a release but can't do the release until the test dependencies compile with 8.4.1.

**Comment by ndmitchell** [comment]
Why can't you make a release until then? For people downstream of you we can start testing our packages with it now, which has benefits for the infrastructure. If it doesn't work with 8.4.1 then ho hum, it's strictly less worse than it is now.

**Comment by mpickering** [comment]
It is irresponsible to release a package if you can't run the tests. 

You could say the exact same thing about every downstream package which is blocking this release. 10 days ago I devoted some of the limited time which I allocate to maintaining this package to trying to cut a release. It was blocked by the downstream dependencies so it will have to wait until next time I want to perform some maintenance.

**Comment by ndmitchell** [comment]
That is of course a perfectly reasonable approach to take, and I hope your test dependencies follow through. Thanks for the maintenance time, I'll buy you a beer next time we meet!
